**Symmetry problem and solution using xavier and He**

In [ ]:
#Xavier method
import math
fin=10
fout=20
w=2/(fin+fout)
w=math.sqrt(w)
print(w)


0.2581988897471611


In [ ]:
import torch.nn as nn
layer=nn.Linear(10,20)
w=nn.init.xavier_normal_(layer.weight)
print(w)

Parameter containing:
tensor([[ 0.0194, -0.0821, -0.3833, -0.5459,  0.3243,  0.4913,  0.2716,  0.7047,
         -0.1143,  0.2401],
        [ 0.1367,  0.1737,  0.4701, -0.1421,  0.1461, -0.0822, -0.3025, -0.3309,
          0.1846,  0.0180],
        [ 0.1353, -0.0685, -0.1716, -0.2262,  0.2860, -0.3100, -0.5104, -0.1258,
          0.3909,  0.3222],
        [-0.0177,  0.1647, -0.1780, -0.0576,  0.2357, -0.3476,  0.1100,  0.3938,
          0.2471, -0.0029],
        [ 0.0923,  0.2937, -0.1664, -0.0627,  0.0662,  0.1294, -0.4404,  0.2057,
         -0.0639, -0.5268],
        [ 0.0502,  0.1371, -0.1511,  0.2928,  0.1136, -0.1737, -0.1285, -0.1330,
         -0.5127, -0.1955],
        [-0.3111, -0.0963,  0.2940, -0.0757, -0.0945, -0.0920,  0.1018,  0.0776,
         -0.5845, -0.0483],
        [-0.1595, -0.4443,  0.5629,  0.2849, -0.4144, -0.2620, -0.2503, -0.4277,
         -0.4444, -0.1077],
        [ 0.0197, -0.2712, -0.2800, -0.2741,  0.1257,  0.1147,  0.0682,  0.2032,
         -0.5171,  0.2783

In [ ]:
import torch.nn as nn
layer=nn.Linear(10,20)
w=nn.init.xavier_uniform_(layer.weight)
print(w)

Parameter containing:
tensor([[ 0.0379,  0.2488,  0.2406, -0.4266, -0.2249,  0.3378,  0.2800, -0.3917,
         -0.3466,  0.3137],
        [ 0.2013,  0.0211,  0.4426, -0.1261,  0.2730,  0.1274,  0.1385, -0.1030,
          0.1226,  0.3360],
        [ 0.3348, -0.2921,  0.0814, -0.2433,  0.3210, -0.3283, -0.0066,  0.1915,
         -0.2848, -0.2871],
        [ 0.1871, -0.3442,  0.2882,  0.0039, -0.2257, -0.0628, -0.2855, -0.3873,
          0.1978, -0.0976],
        [-0.3667,  0.0048, -0.3744, -0.4147, -0.1360, -0.4319,  0.0979,  0.3905,
         -0.1543, -0.0252],
        [ 0.0928, -0.0372,  0.0541, -0.4171, -0.2145,  0.0865,  0.1690, -0.3783,
          0.1814,  0.4214],
        [ 0.2137,  0.3084,  0.1177,  0.1310,  0.2460,  0.1175,  0.1080,  0.4302,
         -0.4241,  0.3483],
        [ 0.1565, -0.3185, -0.1529,  0.4309,  0.1276,  0.0132,  0.2985, -0.2561,
         -0.2279,  0.3085],
        [ 0.1985, -0.0005, -0.2197,  0.3774, -0.0584, -0.3862, -0.3705,  0.0826,
         -0.1217, -0.0322

In [ ]:
#He method
import math
fin=100
w=2/fin
w=math.sqrt(w)
print(w)

0.1414213562373095


In [ ]:
import torch.nn as nn
layer=nn.Linear(20,10)
w=nn.init.kaiming_normal_(layer.weight)
print(w)

Parameter containing:
tensor([[-0.2889, -0.5657,  0.1968, -0.2960, -0.3439, -0.0043,  0.1532, -0.1588,
          0.2068,  0.0317, -0.6786, -0.1143,  0.3434, -0.0049,  0.1714,  0.5023,
          0.0741,  0.2360,  0.5833, -0.0390],
        [-0.1639,  0.2429, -0.3910, -0.0108,  0.2219, -0.0491, -0.1904, -0.6115,
          0.0619, -0.7093, -0.4081,  0.0625, -0.4342, -0.1296, -0.3182,  0.4912,
         -0.0959, -0.1830, -0.2956,  0.0116],
        [ 0.2066,  0.0110,  0.4001,  0.2430,  0.5058, -0.4528, -0.3009,  0.0017,
          0.1162, -0.0476, -0.2689,  0.2797,  0.4655,  0.1040, -0.3419,  0.1997,
          0.2274, -0.1819,  0.0707,  0.0386],
        [ 0.0409,  0.2164,  0.2722, -0.1113,  0.1433,  0.1565,  0.1510,  0.3188,
          0.1721,  0.5742,  0.1415, -0.2841,  0.0142, -0.2486, -0.5001, -0.4747,
         -0.4862, -0.3862,  0.1542, -0.5585],
        [-0.3033,  0.0685,  0.5335,  0.4495, -0.2779,  0.0368, -0.0158,  0.3359,
          0.0462, -0.0701,  0.1652, -0.6334, -0.0402, -0.9760,  0

In [ ]:
import torch.nn as nn
layer=nn.Linear(20,10)
w=nn.init.kaiming_uniform_(layer.weight)
print(w)

Parameter containing:
tensor([[-0.0270,  0.3644, -0.0788, -0.3439, -0.3657, -0.2094, -0.0349,  0.5071,
          0.1566,  0.2778, -0.2483,  0.0025, -0.3371, -0.5328,  0.1340,  0.0253,
          0.0847,  0.0083, -0.0568,  0.3031],
        [-0.5174,  0.2884,  0.3852, -0.3207,  0.5389, -0.0724,  0.1070, -0.5284,
          0.3758,  0.0621,  0.2691,  0.4143, -0.4805,  0.4732,  0.0336,  0.4263,
          0.4598, -0.1727, -0.0534, -0.5214],
        [-0.2362,  0.4775, -0.2244,  0.2153,  0.0897, -0.3456, -0.2981, -0.5275,
         -0.2367, -0.3598, -0.4263, -0.2834,  0.1421, -0.3683,  0.0088,  0.0552,
         -0.2330,  0.0831,  0.1745, -0.0198],
        [ 0.1744,  0.3169,  0.5105,  0.3476,  0.5151, -0.1451, -0.3365, -0.4007,
         -0.4158, -0.3148, -0.1097,  0.4602,  0.2755,  0.4767, -0.3032,  0.3342,
         -0.4143, -0.3256, -0.0180, -0.3352],
        [-0.3227, -0.1527,  0.1762,  0.4074, -0.1243,  0.0929, -0.2027,  0.5122,
          0.0931,  0.2139, -0.4438,  0.3962, -0.0202,  0.1650, -0

In [ ]:
#diff between Havier and He for Relu
import torch
import torch.nn as nn

torch.manual_seed(0)

def dead_relu_experiment(init_type):
    x = torch.randn(1000, 100)  # input
    dead_counts = []

    for layer_idx in range(50):
        layer = nn.Linear(100, 100)

        if init_type == "xavier":
            nn.init.xavier_normal_(layer.weight)
        else:  # he
            nn.init.kaiming_normal_(layer.weight, nonlinearity="relu")

        x = layer(x)
        x = torch.relu(x)

        # Count dead neurons (output always zero)
        dead_neurons = (x.abs().sum(dim=0) == 0).sum().item()
        dead_counts.append(dead_neurons)

    print(f"\n{init_type.upper()} initialization")
    for i, d in enumerate(dead_counts):
        print(f"Layer {i+1}: dead neurons = {d}/100")

dead_relu_experiment("xavier")
dead_relu_experiment("he")



XAVIER initialization
Layer 1: dead neurons = 0/100
Layer 2: dead neurons = 0/100
Layer 3: dead neurons = 1/100
Layer 4: dead neurons = 2/100
Layer 5: dead neurons = 2/100
Layer 6: dead neurons = 3/100
Layer 7: dead neurons = 3/100
Layer 8: dead neurons = 10/100
Layer 9: dead neurons = 16/100
Layer 10: dead neurons = 30/100
Layer 11: dead neurons = 35/100
Layer 12: dead neurons = 38/100
Layer 13: dead neurons = 38/100
Layer 14: dead neurons = 54/100
Layer 15: dead neurons = 48/100
Layer 16: dead neurons = 51/100
Layer 17: dead neurons = 47/100
Layer 18: dead neurons = 48/100
Layer 19: dead neurons = 49/100
Layer 20: dead neurons = 51/100
Layer 21: dead neurons = 50/100
Layer 22: dead neurons = 50/100
Layer 23: dead neurons = 48/100
Layer 24: dead neurons = 44/100
Layer 25: dead neurons = 49/100
Layer 26: dead neurons = 61/100
Layer 27: dead neurons = 53/100
Layer 28: dead neurons = 54/100
Layer 29: dead neurons = 36/100
Layer 30: dead neurons = 52/100
Layer 31: dead neurons = 51/100
L